<!DOCTYPE html>
<html lang="pt-AO">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduConnect</title>
    <link rel="stylesheet" href="../../../public/css/forms.css">
    <link rel="stylesheet" href="../../../public/css/tokens.css">


</head>

<body>

    <div class="login-modal">

        <div class="logo">
            <img src="" alt=" ">
        </div>

        <h3>EduConnect</h3>
        <p class="subtitle">Plataforma Educacional Multi-Escola</p>

        <a href="../user/login.phtml" class="admin-link">Entrar como Usuário normal</a>
        <form action="" method="post" class="form">

            <div class="input-box">
                <label for="email">Email</label>
                <input type="email" placeholder="seuemail@gmail.com" id="email" name="email">
            </div>

            <div class="input-box">
                <label for="password">Senha</label>
                <input type="password" placeholder="Sua Senha" id="password" name="password">
            </div>
            <input type="submit" value="Entrar" class="btn">
        </form>

        <div class="register">
            <p>
                Não tem uma conta?
                <a href="registerAdmin.phtml">Cadastre-se aqui</a>
            </p>
        </div>


    </div>

</body>

</html>