<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="<?=URL?>admin/login_admin" method="post">
        <input type="email" name="email" id="email" required placeholder="Email">
        <input type="password" name="password" id="password" required placeholder="Password">
        <input type="submit" value="Entrar">
    </form>
</body>
</html>