<?php
$admin = new AdminController;
$admin->add_standard_admin();
?>
<!DOCTYPE html>
<html lang="pt-AO">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduConnect</title>
    <link rel="stylesheet" href="<?= URL ?>public/css/forms.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/tokens.css">
    <script src="<?= URL ?>public/js/passwordsControl.js" defer></script>
    <link rel="shortcut icon" href="<?= URL ?>public/assets/icons/favicon.svg" type="image/x-icon">

</head>

<body>

    <div class="login-modal">

        <div class="logo">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-graduation-cap-icon lucide-graduation-cap">
                <path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z" />
                <path d="M22 10v6" />
                <path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5" />
            </svg>
        </div>

        <h3>EduConnect</h3>
        <p class="subtitle">Plataforma Educacional Multi-Escola</p>

        <a href="<?= URL ?>user/login" class="admin-link">Entrar como Usuário</a>
        <form action="<?= URL ?>admin/login_admin" method="post" class="form">

            <div class="input-box">
                <label for="email">Email</label>
                <input type="email" placeholder="seuemail@gmail.com" id="email" name="email" class="id-input" required>
            </div>

            <div class="input-box">
                <label for="password">Senha</label>
                <div class="input-senha">
                    <input type="password" placeholder="Sua Senha" id="password" name="password" autocomplete="off" minlength="8" maxlength="25" required>
                    <button type="button" class="btn-hide-senha">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-eye-icon lucide-eye eye">
                            <path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0" />
                            <circle cx="12" cy="12" r="3" />
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-eye-off-icon lucide-eye-off eye">
                            <path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49" />
                            <path d="M14.084 14.158a3 3 0 0 1-4.242-4.242" />
                            <path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143" />
                            <path d="m2 2 20 20" />
                        </svg>
                    </button>

                </div>
            </div>

            <input type="submit" value="Entrar" class="btn">

        </form>

    </div>

</body>

</html>