<!DOCTYPE html>
<html lang="pt-AO">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduConnect</title>
    <script src="<?= URL ?>public/js/admin.js" defer></script>
 <link rel="stylesheet" href="<?= URL ?>public/css/forms.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/tokens.css">

</head>

<body>

    <div class="register-modal">

        <div class="logo">
            <img src="" alt=" ">
        </div>

        <h2>Novo Administrador</h2>
        <p class="subtitle">EduConnect</p>

        <form action="" method="post" class="form">

            <div class="input-box">
                <label for="userName">Nome Completo</label>
                <input type="text" placeholder="Seu nome Completo" required id="userName" name="userName">
            </div>

            <div class="input-box">
                <label for="userEmail">Email</label>
                <input type="email" placeholder="seuemail@gmail.com" required id="userEmail" name="userEmail">
            </div>

            <div class="input-box">
                <label for="">Perfil</label>
                <label for="fotoAdmin" class="labelFile">
                    <input type="file" name="fotoAdmin" id="fotoAdmin" class="fotoAdmin" hidden>
                    Escolher ficheiro.
                    <span class="fileName">Nenhum ficheiro escolhido</span>
                </label>
            </div>


            <div class="input-box">
                <label for="userPassword">Senha</label>
                <input type="password" placeholder="Sua senha" required id="userPassword" name="userPassword">
            </div>

            <div class="input-box">
                <label for="confirmPassowrd">Confirmar Senha</label>
                <input type="password" placeholder="Confirme sua senha" required id="confirmPassowrd" name="confirmPassowrd">
            </div>

            <input type="submit" value="Cadastrar" class="btn">

        </form>

    </div>

</body>

</html>