<?php
    require_once './app/views/layouts/adminMain.phtml';
?>

<section class="security">
    <section class="up-section">
        <div class="icon-back">
            <a href="<?= URL ?>admin/settings">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-left-icon lucide-arrow-left"><path d="m12 19-7-7 7-7"/><path d="M19 12H5"/></svg>
                <p>Voltar</p>
            </a>
        </div>
        <h4>Segurança</h4>
        <p>Gerir a segurança da sua conta</p>
    </section>
    <section class="alter-pass-area">
        <div class="title-area">
            <div class="icon-security-area">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield-icon lucide-shield"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/></svg>

            </div>
            <div class="title-desc">
                <h4>Alterar Senha</h4>
                <p>Atualize a senha da sua conta</p>
            </div>
        </div>
        <div class="alter-pass-form">
            <form action="<?= URL ?>admin/change_password" method="post" class="alter-form">
                <div class="input-box">
                    <label for="currentPass">Senha Actual</label>
                    <input type="password" name="currentPassword" id="currentPass" placeholder="Digite a senha actual" autocomplete="off" minlength="8" maxlength="25" required>
                </div>
                <div class="input-box">
                    <label for="newPass">Nova Senha</label>
                    <input type="password" name="newPassword" id="newPass" placeholder="Digite a nova senha" autocomplete="off" minlength="8" maxlength="25" required>
                </div>
                <div class="input-box">
                    <label for="confirmNewPass">Confirmar Nova Senha</label>
                    <input type="password" name="confirmNewPassword" id="confirmNewPass" placeholder="Digite novamente a nova senha" autocomplete="off" minlength="8" maxlength="25" required>
                </div>

                <input type="hidden" name="id" value="<?= $_SESSION['id'] ?>">
                <div class="btn-box">
                    <button type="button">Cancelar</button>
                    <button type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-save-icon lucide-save"><path d="M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z"/><path d="M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7"/><path d="M7 3v4a1 1 0 0 0 1 1h7"/></svg>

                        <p>Alterar Senha</p>
                    </button>
                </div>
            </form>
        </div>
    </section>
    <section class="security-tips-area">
        <div class="title-area">
            <div class="icon-lock-area">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-lock-icon lucide-lock"><rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>

            </div>
            <div class="title-desc">
                <h4>Dicas de Segurança</h4>
            </div>
        </div>
        <div class="tips-list">
            <div class="tip-item">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-dot-icon lucide-dot"><circle cx="12.1" cy="12.1" r="1"/></svg>
                <p>Use uma senha única que não utiliza em outros serviços</p>
            </div>
            <div class="tip-item">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-dot-icon lucide-dot"><circle cx="12.1" cy="12.1" r="1"/></svg>
                <p>Altere a sua senha regularmente para manter a conta segura</p>
            </div>
            <div class="tip-item">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-dot-icon lucide-dot"><circle cx="12.1" cy="12.1" r="1"/></svg>
                <p>Nunca partilhe a sua senha com terceiros</p>
            </div>
        </div>
    </section>
</section>