<?php
    require_once './app/views/layouts/usersMain.phtml';
    $class_id = $_SESSION['class_id'];

    $class = new ClassController;
    $messages = new MessageController;
    $chats = new ChatController;

    $class_chat = $chats->get_chat($class_id, $_SESSION['school_id']);
    $class_data = $class->get_class_data($class_id, $_SESSION['school_id']);
    $students = $class->get_class_students($class_id);
    $school_students = $class->fetch_school_students($_SESSION['school_id']);
?>

<div class="current-class-wrapper">
    <div class="overlay-feed"></div>
    <div class="overlay-current-class"></div>
    <section id="current-class-section">
        <div class="icon-back">
            <a href="<?= URL ?>teacher/classes">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-left-icon lucide-arrow-left">
                    <path d="m12 19-7-7 7-7" />
                    <path d="M19 12H5" />
                </svg>

                <p>Voltar</p>
            </a>
        </div>
        <div class="class-info">
            <div class="top-side">
                <div class="nome-desc-class">
                    <h4><?= $class_data['class'] ?></h4>
                </div>
                <button id="btn-show-modal">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-plus-icon lucide-user-plus">
                        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                        <circle cx="9" cy="7" r="4" />
                        <line x1="19" x2="19" y1="8" y2="14" />
                        <line x1="22" x2="16" y1="11" y2="11" />
                    </svg>

                    <p>Gerir Alunos</p>
                </button>
                <div class="modal-students-list">
                    <div class="head-modal">
                        <div class="up-side">
                            <h3>Gerir Alunos</h3>
                            <img src="<?= URL ?>public/assets/icons/x.png" id="close-menu-m">
                        </div>
                        <div class="search-class">
                            <div class="icon-search-class">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-search-icon lucide-search">
                                    <path d="m21 21-4.34-4.34" />
                                    <circle cx="11" cy="11" r="8" />
                                </svg>

                            </div>
                            <input type="text" name="searchUser" id="searchUser" placeholder="Pesquisar alunos">
                        </div>
                    </div>
                    <div class="list" id="usersResults">
                        <?php if (!empty($school_students)):?>
                            <?php foreach ($school_students as $student):?>
                                <div class="student-item" >
                                    <div class="info-student">
                                        <div class="student-profile">
                                            <?php if ($student['foto'] !== "null"):?>
                                                <img src="<?= URL. "public/". $student['foto'] ?>">
                                            <?php else:?>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                                                    <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                                                    <circle cx="12" cy="11" r="4" />
                                                    <circle cx="12" cy="12" r="10" />
                                                </svg>
                                            <?php endif;?>
                                        </div>
                                        <div class="student-name-email">
                                            <h4><?= $student['nome'] ?></h4>
                                            <p><?= $student['email'] ?></p>
                                        </div>
                                    </div>
                                    <button class="student-action add" onclick="window.location.href='<?= URL ?>class/add_class_student/<?= $student['id'] ?>/<?= $class_id ?>'">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-plus-icon lucide-user-plus">
                                            <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                                            <circle cx="9" cy="7" r="4" />
                                            <line x1="19" x2="19" y1="8" y2="14" />
                                            <line x1="22" x2="16" y1="11" y2="11" />
                                        </svg>


                                        <p>Adicionar</p>
                                    </button>
                                </div>
                            <?php endforeach;?>
                        <?php endif;?>
                    </div>
                    <div class="bottom-side">
                        <p><?= $class_data['school_students'] === 1 ? $class_data['school_students']. " Aluno" : $class_data['school_students']. " Alunos"?></p>
                        <button class="btn-close-student-modal">Fechar</button>
                    </div>
                </div>
            </div>
            <div class="info-nome-teacher">
                <div class="teacher-photo">
                    <?php if ($class_data['foto'] !== "null"):?>
                        <img src="<?= URL. "public/". $class_data['foto'] ?>">
                    <?php else:?>
                        <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                            <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                            <circle cx="12" cy="11" r="4" />
                            <circle cx="12" cy="12" r="10" />
                        </svg>
                    <?php endif;?>
                </div>
                <div class="nome-teacher">
                    <h3><?= $class_data['teacher'] ?></h3>
                    <p>Professor</p>
                </div>
            </div>
        </div>
        <div class="tabs-class">
            <button class="tab-class activeClass" data-current-class="chat-section">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-square-icon lucide-message-square">
                    <path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z" />
                </svg>

                <p>Chat</p>
            </button>
            <button class="tab-class" data-current-class="students-manegement">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users-icon lucide-users">
                    <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                    <path d="M16 3.128a4 4 0 0 1 0 7.744" />
                    <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
                    <circle cx="9" cy="7" r="4" />
                </svg>

                <p>Alunos (<?= $class_data['students'] ?>)</p>
            </button>
        </div>
        <!--CHAT SECTION-->
        <div class="chat-section class-content active">
            <div class="messages-box" id="messages-box"></div>
            <div class="send-message-box">
                <div class="img-profile">
                    <?php if ($_SESSION['photo'] !== "null"):?>
                        <img src="<?= URL. "public/". $_SESSION['photo'] ?>">
                    <?php else:?>
                        <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                            <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                            <circle cx="12" cy="11" r="4" />
                            <circle cx="12" cy="12" r="10" />
                        </svg>
                    <?php endif;?>
                </div>
                <form action="<?= URL ?>message/send_message/<?= $class_id ?>/<?= $_SESSION['role'] ?>" method="POST" class="message-input">
                    <div class="input-box">
                        <textarea name="content" class="fileName" id="msg-content" placeholder="Escreva uma mensagem"></textarea>
                    </div>

                    <input type="hidden" name="chat" value="<?= $class_chat ?>">
                    <input type="hidden" name="school" value="<?= $_SESSION['school_id'] ?>">
                    <input type="hidden" name="user" value="<?= $_SESSION['id'] ?>">

                    <div class="msg-action-btns">
                        <button type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-send-icon lucide-send">
                                <path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z" />
                                <path d="m21.854 2.147-10.94 10.939" />
                            </svg>
                            <p>Enviar</p>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <!--STUDENTS MANAGEMENT-->
        <div class="students-manegement class-content">
            <?php if (!empty($students)): ?>
                <?php foreach ($students as $s): ?>
                    <div class="student-item">
                        <div class="info-student">
                            <div class="student-profile">
                                <?php if ($s['foto'] !== "null"):?>
                                    <img src="<?= URL. "public/". $s['foto'] ?>">
                                <?php else:?>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                                        <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                                        <circle cx="12" cy="11" r="4" />
                                        <circle cx="12" cy="12" r="10" />
                                    </svg>
                                <?php endif;?>
                            </div>
                            <div class="student-name-email">
                                <h4><?= $s['nome'] ?></h4>
                                <p><?= $s['email'] ?></p>
                            </div>
                        </div>
                        <button class="student-action" onclick="window.location.href='<?= URL ?>class/remove_class_student/<?= $s['id'] ?>/<?= $class_id ?>'">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-minus-icon lucide-user-minus">
                                <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                                <circle cx="9" cy="7" r="4" />
                                <line x1="22" x2="16" y1="11" y2="11" />
                            </svg>

                            <p>Remover</p>
                        </button>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>

    </section>
</div>
<input type="hidden" name="url" id="url" value="<?= URL ?>">
<input type="hidden" name="urlC" id="urlC" value="<?= URL ?>">

<input type="hidden" id="schoolId" value="<?= $_SESSION['school_id'] ?>">
<input type="hidden" id="userRole" value="aluno">
<input type="hidden" id="type" value="classSearch">
<script src="<?= URL ?>public/js/searchUsers.js"></script>

<input type="hidden" id="school" value="<?= $_SESSION['school_id'] ?>">
<input type="hidden" id="chat" value="<?= $class_chat ?>">
<input type="hidden" id="user" value="<?= $_SESSION['id'] ?>">
<script src="<?= URL ?>public/js/chatRealTime.js"></script>

<?php require_once './app/views/layouts/closure.phtml' ?>