<?php
require_once './app/views/layouts/usersMain.phtml'
?>

<div class="class-wrapper">
    <div class="overlay-class"></div>
    <style>
        .selectedClass {
            background-color: var(--AccentBlue);
        }

        .selectedClass a {
            color: var(--Background) !important;
        }
    </style>
    <section id="class-section">
        <div class="header-class">
            <div class="title-class">
                <h2>Turmas</h2>
                <p>Turmas que leciona</p>
            </div>
            <button class="btn-new-class">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus-icon lucide-plus"><path d="M5 12h14"/><path d="M12 5v14"/></svg>

                Nova Turma
            </button>
        </div>

        <!--CLASS MODAL-->

        <div class="class-modal">
            <div class="class-modal-header">
                <h3>Nova Turma</h3>
                <p>Crie uma nova turma para organizar alunos e professores.</p>

                <button class="close-icon-btn">
                    <img src="<?= URL ?>public/assets/icons/x.png" alt="close-icon">
                </button>
            </div>
            <form action="" class="class-form" method="post">
                <div class="input-box">
                    <label for="">Nome da Turma *</label>
                    <input type="text" name="" id="class-name" placeholder="Ex: Matemática 12ª A">
                </div>
                <div class="input-box">
                    <label for="">Professor Responsável *</label>
                    <select name="type" id="type-publication">
                        <option value="post">Selecione o professor</option>
                    </select>
                </div>


                <div class="btn-create-box">
                    <button>Cancelar</button>
                    <button>Criar</button>
                </div>

                <input type="hidden" name="user" value="<?= $_SESSION['id'] ?>">
                <input type="hidden" name="school" value="<?= $_SESSION['school_id'] ?>">
            </form>
        </div>

        <!--SEARCH CLASS BOX-->
        <div class="search-class">
            <div class="icon-search-class">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-search-icon lucide-search"><path d="m21 21-4.34-4.34"/><circle cx="11" cy="11" r="8"/></svg>

            </div>
            <input type="text" name="" id="" placeholder="Pesquisar Turmas">
        </div>

        <!--CLASS CARDS SECTION-->
        <div class="class-cards">
            <a href="<?= URL ?>teacher/currentClass" class="class-card">
                <h3>Matemática 11ª B</h3>
                <p class="desc-turma">Turma de Matemática para 11ª Classe - Turno da Manhã</p>
                <div class="prof-info">
                    <div class="prof-profile-img">
                        <img src="" alt=" ">
                    </div>
                    <h4>Nome do Prof.</h4>
                </div>
                <div class="students-info">
                    <div class="icon-students">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users-icon lucide-users"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><path d="M16 3.128a4 4 0 0 1 0 7.744"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/></svg>

                    </div>
                    <h4>nº alunos</h4>
                </div>
            </a>
            <a href="" class="class-card">
                <h3>Português 11ª B</h3>
                <p class="desc-turma">Turma de Português para 11ª Classe - Turno da Manhã</p>
                <div class="prof-info">
                    <div class="prof-profile-img">
                        <img src="" alt=" ">
                    </div>
                    <h4>Nome do Prof.</h4>
                </div>
                <div class="students-info">
                    <div class="icon-students">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users-icon lucide-users"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><path d="M16 3.128a4 4 0 0 1 0 7.744"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/></svg>

                    </div>
                    <h4>nº alunos</h4>
                </div>
            </a>
            <a href="" class="class-card">
                <h3>Português 11ª B</h3>
                <p class="desc-turma">Turma de Português para 11ª Classe - Turno da Manhã</p>
                <div class="prof-info">
                    <div class="prof-profile-img">
                        <img src="" alt=" ">
                    </div>
                    <h4>Nome do Prof.</h4>
                </div>
                <div class="students-info">
                    <div class="icon-students">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users-icon lucide-users"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><path d="M16 3.128a4 4 0 0 1 0 7.744"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/></svg>

                    </div>
                    <h4>nº alunos</h4>
                </div>
            </a>
            <a href="" class="class-card">
                <h3>Português 11ª B</h3>
                <p class="desc-turma">Turma de Português para 11ª Classe - Turno da Manhã</p>
                <div class="prof-info">
                    <div class="prof-profile-img">
                        <img src="" alt=" ">
                    </div>
                    <h4>Nome do Prof.</h4>
                </div>
                <div class="students-info">
                    <div class="icon-students">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users-icon lucide-users"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><path d="M16 3.128a4 4 0 0 1 0 7.744"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/></svg>

                    </div>
                    <h4>nº alunos</h4>
                </div>
            </a>
        </div>
    </section>
</div>

<?php
require_once './app/views/layouts/closure.phtml'
?>