<?php
require_once './app/views/layouts/usersMain.phtml'
?>

<div class="current-class-wrapper">
    <div class="overlay-current-class"></div>
    <section id="current-class-section">
        <div class="icon-back">
            <a href="<?= URL ?>teacher/classes">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-left-icon lucide-arrow-left">
                    <path d="m12 19-7-7 7-7" />
                    <path d="M19 12H5" />
                </svg>

                <p>Voltar</p>
            </a>
        </div>
        <div class="class-info">
            <div class="top-side">
                <div class="nome-desc-class">
                    <h4>Nome Turma</h4>
                    <p>Descrição Turma</p>
                </div>
                <button id="btn-show-modal">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-plus-icon lucide-user-plus">
                        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                        <circle cx="9" cy="7" r="4" />
                        <line x1="19" x2="19" y1="8" y2="14" />
                        <line x1="22" x2="16" y1="11" y2="11" />
                    </svg>

                    <p>Gerir Alunos</p>
                </button>
                <div class="modal-students-list">
                    <div class="head-modal">
                        <div class="up-side">
                            <h3>Gerir Alunos</h3>
                            <img src="<?= URL ?>public/assets/icons/x.png" alt=" " id="close-menu-m">
                        </div>
                        <div class="search-class">
                            <div class="icon-search-class">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-search-icon lucide-search">
                                    <path d="m21 21-4.34-4.34" />
                                    <circle cx="11" cy="11" r="8" />
                                </svg>

                            </div>
                            <input type="text" name="" id="" placeholder="Pesquisar alunos">
                        </div>
                    </div>
                    <div class="list">
                        <div class="student-item">
                            <div class="info-student">
                                <div class="student-profile">
                                    <img src="" alt=" ">
                                </div>
                                <div class="student-name-email">
                                    <h4>Nome Estudante Nome Estudante</h4>
                                    <p>emailestudanteteste</p>
                                </div>
                            </div>
                            <button class="student-action add">
                               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-plus-icon lucide-user-plus"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" x2="19" y1="8" y2="14"/><line x1="22" x2="16" y1="11" y2="11"/></svg>


                                <p>Adicionar</p>
                            </button>
                        </div>
                        <div class="student-item">
                            <div class="info-student">
                                <div class="student-profile">
                                    <img src="" alt=" ">
                                </div>
                                <div class="student-name-email">
                                    <h4>Nome Estudante Nome Estudante</h4>
                                    <p>emailestudanteteste</p>
                                </div>
                            </div>
                            <button class="student-action add">
                               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-plus-icon lucide-user-plus"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" x2="19" y1="8" y2="14"/><line x1="22" x2="16" y1="11" y2="11"/></svg>


                                <p>Adicionar</p>
                            </button>
                        </div>
                       
                        <div class="student-item">
                            <div class="info-student">
                                <div class="student-profile">
                                    <img src="" alt=" ">
                                </div>
                                <div class="student-name-email">
                                    <h4>Nome Estudante Nome Estudante</h4>
                                    <p>emailestudanteteste</p>
                                </div>
                            </div>
                            <button class="student-action drop">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-minus-icon lucide-user-minus">
                                    <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                                    <circle cx="9" cy="7" r="4" />
                                    <line x1="22" x2="16" y1="11" y2="11" />
                                </svg>

                                <p>Remover</p>
                            </button>
                        </div>
                    </div>
                    <div class="bottom-side">
                        <p>Número estudantes</p>
                        <button class="btn-close-student-modal">Fechar</button>
                    </div>
                </div>
            </div>
            <div class="info-nome-teacher">
                <div class="teacher-photo">
                    <img src="" alt=" ">
                </div>
                <div class="nome-teacher">
                    <h3>Nome Prof</h3>
                    <p>Professor</p>
                </div>
            </div>
        </div>
        <div class="tabs-class">
            <button class="tab-class activeClass" data-current-class="pub-class">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-newspaper-icon lucide-newspaper">
                    <path d="M15 18h-5" />
                    <path d="M18 14h-8" />
                    <path d="M4 22h16a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16a2 2 0 0 1-4 0v-9a2 2 0 0 1 2-2h2" />
                    <rect width="8" height="4" x="10" y="6" rx="1" />
                </svg>

                <p>Publicações (1)</p>
            </button>
            <button class="tab-class" data-current-class="chat-section">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-square-icon lucide-message-square">
                    <path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z" />
                </svg>

                <p>Chat (3)</p>
            </button>
            <button class="tab-class" data-current-class="students-manegement">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users-icon lucide-users">
                    <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                    <path d="M16 3.128a4 4 0 0 1 0 7.744" />
                    <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
                    <circle cx="9" cy="7" r="4" />
                </svg>

                <p>Alunos (12)</p>
            </button>
        </div>
        <!--PUBLICATION SECTION-->
        <div class="pub-class active class-content">
            <button class="btn-new-publish">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus-icon lucide-plus">
                    <path d="M5 12h14" />
                    <path d="M12 5v14" />
                </svg>

                Nova Publicação
            </button>
            <!--MODAL NEW PUB CLASS-->
            <div class="feed-modal">
                <div class="feed-modal-header">
                    <h3>Nova Publicação</h3>
                    <p>Compartilhe conteúdo com a comunidade escolar.</p>

                    <button class="close-icon-btn">
                        <img src="<?= URL ?>public/assets/icons/x.png" alt="close-icon">
                    </button>
                </div>
                <form action="<?= URL ?>user/publish" class="publication-form" method="post">
                    <div class="input-box">
                        <label for="type-publication">Tipo de Publicação *</label>
                        <select name="type" id="type-publication">
                            <option value="post">Publicação Normal</option>
                            <?php if (($_SESSION['role'] === 'director') || ($_SESSION['role'] === 'professor')): ?>
                                <option value="aviso">Aviso/Comunicado</option>
                            <?php endif; ?>
                        </select>
                    </div>
                    <div class="input-box">
                        <label for="publication-content">Conteúdo *</label>
                        <textarea name="content" id="publication-content" placeholder="O que deseja compartilhar?"></textarea>
                    </div>
                    <div class="input-box">
                        <label for="">Anexos</label>
                        <label for="publication-file" class="labelFile">
                            <input type="file" name="file" id="publication-file" class="fotoFile" hidden>
                            Anexar Ficheiros.
                            <span class="fileName">Nenhum ficheiro escolhido</span>
                        </label>
                    </div>
                    <div class="btn-publish-box">
                        <button>Cancelar</button>
                        <button>Publicar</button>
                    </div>

                    <input type="hidden" name="user" value="<?= $_SESSION['id'] ?>">
                    <input type="hidden" name="school" value="<?= $_SESSION['school_id'] ?>">
                </form>
            </div>
            <!--PUBLICATION CARDS-->
            <div class="publication-cards" id="posts">
                <?php if (empty($posts)): ?>
                    <h3>Nada para ver</h3>
                <?php else: ?>
                    <?php
                    $publications = array_filter($posts, function ($n) {
                        return $n['tipo'] === 'post';
                    });
                    ?>
                    <?php
                    foreach ($publications as $publication):
                        $interactionsCount = $user->get_interactions($publication['id']);
                        $comments = $user->get_post_comments($publication['id']);
                        $reaction = $user->get_reactions($_SESSION['id'], $publication['id']);
                    ?>
                        <div class="publication-card">
                            <div class="header-publication-card">
                                <div class="info-user-publication-card">
                                    <div class="img-user">
                                        <img src="<?= $publication['foto'] ?>" alt="">
                                    </div>
                                    <div class="name-user">
                                        <h4><?= $publication['user'] ?></h4>
                                        <p><?= $publication['created_at'] ?></p>
                                    </div>

                                </div>
                                <button class="options-publication-card">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-ellipsis-vertical-icon lucide-ellipsis-vertical">
                                        <circle cx="12" cy="12" r="1" />
                                        <circle cx="12" cy="5" r="1" />
                                        <circle cx="12" cy="19" r="1" />
                                    </svg>
                                    <div class="drop-post-card-actions">
                                        <?php if ($_SESSION['id'] === $publication['user_id']): ?>
                                            <div class="drop-post-card-action">
                                                <div class="icon-area">
                                                    <img src="" alt=" ">
                                                </div>
                                                <p>Bloquear comentários</p>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($_SESSION['role'] === 'director' || $_SESSION['role'] === 'professor'): ?>
                                            <div class="drop-post-card-action">
                                                <div class="icon-area">
                                                    <img src="" alt=" ">
                                                </div>
                                                <p>Remover publicação</p>
                                            </div>
                                        <?php endif; ?>
                                        <?php if (!($_SESSION['role'] === 'director' || $_SESSION['role'] === 'professor') && !($_SESSION['id'] === $publication['user_id'])): ?>
                                            <div class="drop-post-card-action">
                                                <div class="icon-area">
                                                    <img src="" alt=" ">
                                                </div>
                                                <p>Sem acções</p>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </button>
                            </div>
                            <div class="publication-card-content">
                                <p><?= $publication['conteudo'] ?></p>
                                <div class="attachment">
                                    <a href="" class="file-info">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-link-icon lucide-link">
                                            <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
                                            <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
                                        </svg>

                                        <div class="file-name">
                                            <p>Nome do ficheiro</p>
                                            <span>Link</span>
                                        </div>
                                    </a>
                                    <a href="" download="" class="btn-download">
                                        Baixar
                                    </a>
                                </div>
                            </div>
                            <div class="reactions-info">
                                <!--Likes info-->
                                <div class="reactions-statistics">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-thumbs-up-icon lucide-thumbs-up">
                                        <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z" />
                                        <path d="M7 10v12" />
                                    </svg> <?= $interactionsCount['likes'] ?>
                                </div>
                                <!--Favorites info-->
                                <div class="reactions-statistics">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-heart-icon lucide-heart">
                                        <path d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5" />
                                    </svg> <?= $interactionsCount['adores'] ?>
                                </div>
                                <!--Comments info-->
                                <div class="reactions-statistics">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-circle-icon lucide-message-circle">
                                        <path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719" />
                                    </svg> <?= $interactionsCount['comments'] ?>
                                </div>
                            </div>
                            <div class="reaction-actions">
                                <form action="<?= URL ?>user/react" method="post">
                                    <input type="hidden" name="user" value=<?= $_SESSION['id'] ?>>
                                    <input type="hidden" name="post" value=<?= $publication['id'] ?>>

                                    <button class="reaction-option thumbs-up <?= $reaction['usuario'] === $_SESSION['id'] && $reaction['post'] === $publication['id'] && $reaction['tipo'] === 'like' ? 'click' : '' ?>" name="type" value="like">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-thumbs-up-icon lucide-thumbs-up">
                                            <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z" />
                                            <path d="M7 10v12" />
                                        </svg>

                                        <p>Gosto</p>
                                    </button>
                                    <button class="reaction-option favorite <?= $reaction['usuario'] === $_SESSION['id'] && $reaction['post'] === $publication['id'] && $reaction['tipo'] === 'adoro' ? 'click' : '' ?>" name="type" value="adoro">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-heart-icon lucide-heart">
                                            <path d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5" />
                                        </svg>

                                        <p>Adoro</p>
                                    </button>
                                </form>
                                <button class="reaction-option comment" id="">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-circle-icon lucide-message-circle">
                                        <path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719" />
                                    </svg>

                                    <p>Comentar</p>
                                </button>
                            </div>
                            <section class="comment-section">
                                <div class="comment-area">
                                    <div class="img-user">
                                        <img src="" alt=" ">
                                    </div>
                                    <form action="<?= URL ?>user/comment" method="post">
                                        <div class="comment-box">
                                            <textarea name="content" placeholder="Escreva um comentário"></textarea>
                                            <input type="hidden" name="user" value="<?= $_SESSION['id'] ?>">
                                            <input type="hidden" name="post" value="<?= $publication['id'] ?>">
                                            <input type="hidden" name="school" value="<?= $publication['school'] ?>">
                                            <button type="submit" class="btn-comment">Publicar</button>
                                        </div>
                                    </form>
                                </div>
                                <?php if (!empty($comments)): ?>
                                    <?php foreach ($comments as $comment): ?>
                                        <div class="show-comment-area">
                                            <div class="img-user">
                                                <img src="" alt=" ">
                                            </div>
                                            <div class="show-comment-box">
                                                <div class="show-comment">
                                                    <h4><?= $comment['usuario'] ?></h4>
                                                    <p><?= $comment['conteudo'] ?></p>
                                                </div>
                                                <span class="comment-time"><?= $comment['created_at'] ?></span>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </section>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
        <!--CHAT SECTION-->
        <div class="chat-section class-content">
            <div class="messages-box">
                <div class="message received">
                    <div class="sender-profile">
                        <img src="" alt=" ">
                    </div>
                    <div class="message-box">
                        <div class="message-content">
                            <h4>Nome Emissor</h4>
                            <p>Conteúdo Mensagem</p>
                        </div>
                        <span>Tempo Enviado</span>
                    </div>
                </div>
                <div class="message received">
                    <div class="sender-profile">
                        <img src="" alt=" ">
                    </div>
                    <div class="message-box">
                        <div class="message-content">
                            <h4>Nome Emissor</h4>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit odio commodi nobis consequuntur reiciendis fuga aut veritatis</p>
                        </div>
                        <span>Tempo Enviado</span>
                    </div>
                </div>
                <div class="message sent">
                    <div class="sender-profile">
                        <img src="" alt=" ">
                    </div>
                    <div class="message-box">
                        <div class="message-content">
                            <h4>Nome Emissor</h4>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <span>Tempo Enviado</span>
                    </div>
                </div>
            </div>
            <div class="send-message-box">
                <div class="img-profile">
                    <img src="" alt=" ">
                </div>
                <div class="message-input">
                    <div class="input-box">
                        <textarea name="" class="fileName" id="msg-content" placeholder="Escreva uma mensagem"></textarea>
                    </div>
                    <div class="msg-action-btns">
                        <label for="publication-file" class="labelFile">
                            <input type="file" name="file" id="publication-file" class="fotoFile" hidden>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-paperclip-icon lucide-paperclip">
                                <path d="m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551" />
                            </svg>
                            Anexar
                        </label>
                        <button type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-send-icon lucide-send">
                                <path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z" />
                                <path d="m21.854 2.147-10.94 10.939" />
                            </svg>
                            <p>Enviar</p>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!--STUDENTS MANAGEMENT-->
        <div class="students-manegement class-content" id="">
            <div class="student-item">
                <div class="info-student">
                    <div class="student-profile">
                        <img src="" alt=" ">
                    </div>
                    <div class="student-name-email">
                        <h4>Nome Estudante Nome Estudante</h4>
                        <p>emailestudanteteste</p>
                    </div>
                </div>
                <button class="student-action">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-minus-icon lucide-user-minus">
                        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                        <circle cx="9" cy="7" r="4" />
                        <line x1="22" x2="16" y1="11" y2="11" />
                    </svg>

                    <p>Remover</p>
                </button>
            </div>
            <div class="student-item">
                <div class="info-student">
                    <div class="student-profile">
                        <img src="" alt=" ">
                    </div>
                    <div class="student-name-email">
                        <h4>Nome Estudante Nome Estudante</h4>
                        <p>emailestudanteteste</p>
                    </div>
                </div>
                <button class="student-action">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-minus-icon lucide-user-minus">
                        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                        <circle cx="9" cy="7" r="4" />
                        <line x1="22" x2="16" y1="11" y2="11" />
                    </svg>

                    <p>Remover</p>
                </button>
            </div>
            <div class="student-item">
                <div class="info-student">
                    <div class="student-profile">
                        <img src="" alt=" ">
                    </div>
                    <div class="student-name-email">
                        <h4>Nome Estudante Nome Estudante</h4>
                        <p>emailestudanteteste</p>
                    </div>
                </div>
                <button class="student-action">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-minus-icon lucide-user-minus">
                        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                        <circle cx="9" cy="7" r="4" />
                        <line x1="22" x2="16" y1="11" y2="11" />
                    </svg>

                    <p>Remover</p>
                </button>
            </div>
        </div>

    </section>
</div>

<?php
require_once './app/views/layouts/closure.phtml'
?>