<?php
require_once './app/views/layouts/usersMain.phtml'
?>

<div class="class-wrapper">
    <section id="class-section">
        <div class="icon-back">
            <a href="<?= URL ?>teacher/classes">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-left-icon lucide-arrow-left"><path d="m12 19-7-7 7-7"/><path d="M19 12H5"/></svg>

                <p>Voltar</p>
            </a>
        </div>
        <div class="class-info">
            <div class="top-side">
                <div class="nome-desc-class">
                    <h4>Nome Turma</h4>
                    <p>Descrição Turma</p>
                </div>
                <button>
                    <img src="" alt="">
                    <p>Gerir Alunos</p>
                </button>
            </div>
            <div class="info-nome-teacher">
                <img src="" alt="">
                <div class="nome-teacher">
                    <h3>Nome Prof</h3>
                    <p>Professor</p>
                </div>
            </div>
        </div>
        <h1>Class</h1>
    </section>
</div>

<?php
require_once './app/views/layouts/closure.phtml'
?>