<?php 
    require_once './app/views/layouts/usersMain.phtml';
    $message = new MessageController;
    $unread_messages = $message->get_unread_messages($_SESSION['id']);
?>
<div class="message-wrapper">
    <style>
        .selectedMessages {
            background-color: var(--AccentBlue);
        }

        .selectedMessages:hover {
            background-color: var(--AccentBlueHover);
        }

        .selectedMessages a {
            color: var(--Background) !important;
        }

        li:not(.selectedMessages):hover {
            background-color: var(--Muted);
        }
    </style>
    <section id="message-section">
        <div class="header-messages">
            <div class="title-message">
                <h2>Mensagens</h2>
                <p>Chat das suas turmas</p>
            </div>
        </div>
        <div class="list-messages">
            <?php if(!empty($unread_messages)):?>
                <?php foreach ($unread_messages as $urm):?>
                    <a href="<?= URL ?>message/view_message/<?= $urm['id'] ?>/<?= $_SESSION['id'] ?>/<?= $urm['turma_id'] ?>/professor" class="message-item">
                        <div class="sender-profile">
                            <?php if ($urm['remetente_foto'] !== "null"):?>
                                <img src="<?= URL. "public/". $urm['remetente_foto'] ?>">
                            <?php else:?>
                                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                                    <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                                    <circle cx="12" cy="11" r="4" />
                                    <circle cx="12" cy="12" r="10" />
                                </svg>
                            <?php endif;?>
                        </div>
                        <div class="desc-message">
                            <div class="info-class">
                                <h3><?= $urm['turma'] ?></h3>
                                <div class="sms-counter"><?= $urm['id'] ?></div>
                            </div>
                            <div class="info-sms">
                                <p><span><?= $urm['remetente'] ?>:</span> <?= $urm['conteudo'] ?></p>
                                <span><?= $urm['hora_envio'] ?></span>
                            </div>
                        </div>
                    </a>
                <?php endforeach;?>
            <?php endif;?>
        </div>

    </section>
</div>

<?php require_once './app/views/layouts/closure.phtml' ?>