<?php
require_once './app/views/layouts/usersMain.phtml'
?>

<div class="message-wrapper">
    <style>
        .selectedMessages {
            background-color: var(--AccentBlue);
        }
        .selectedMessages a{
            color: var(--Background) !important;
        }
    </style>
    <section id="message-section">
        <h1>Mensagens</h1>
    </section>
</div>

<?php
require_once './app/views/layouts/closure.phtml'
?>