<?php
require_once './app/views/layouts/usersMain.phtml'
?>
<div class="message-wrapper">
    <style>
        .selectedMessages {
            background-color: var(--AccentBlue);
        }

        .selectedMessages:hover {
            background-color: var(--AccentBlueHover);
        }

        .selectedMessages a {
            color: var(--Background) !important;
        }

        li:not(.selectedMessages):hover {
            background-color: var(--Muted);
        }
    </style>
    <section id="message-section">
        <div class="header-messages">
            <div class="title-message">
                <h2>Mensagens</h2>
                <p>Chat das suas turmas</p>
            </div>
        </div>
        <div class="list-messages">
            <a href="<?= URL ?>teacher/classes" class="message-item">
                <div class="sender-profile">
                    <!--<img src="" alt=" ">-->
                    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                        <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                        <circle cx="12" cy="11" r="4" />
                        <circle cx="12" cy="12" r="10" />
                    </svg>
                </div>
                <div class="desc-message">
                    <div class="info-class">
                        <h3>Nome Turma</h3>
                        <div class="sms-counter">2</div>
                    </div>
                    <div class="info-sms">
                        <p><span>Nome emissor:</span> Conteúdo da mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates, odio itaque! Exercitationem in labore minus omnis id vel porro nam? Nulla quo, odio dicta dolor minima fugit. Tenetur, fugit atque Lorem ipsum, dolor sit amet consectetur adipisicing elit. Adipisci consequatur commodi fugiat. Quos incidunt facere nesciunt fugiat ullam repellat, deserunt ea eum voluptatibus temporibus dolores, nobis nulla dolorum aliquam at!.</p>
                        <span>Tempo enviado</span>
                    </div>
                </div>
            </a>
            <a href="<?= URL ?>teacher/classes" class="message-item">
                <div class="sender-profile">
                    <!--<img src="" alt=" ">-->
                    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                        <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                        <circle cx="12" cy="11" r="4" />
                        <circle cx="12" cy="12" r="10" />
                    </svg>
                </div>
                <div class="desc-message">
                    <div class="info-class">
                        <h3>Nome Turma</h3>
                        <div class="sms-counter">2</div>
                    </div>
                    <div class="info-sms">
                        <p><span>Nome emissor:</span> Conteúdo da mensagem</p>
                        <span>Tempo enviado</span>
                    </div>
                </div>
            </a>
        </div>

    </section>
</div>

<?php
require_once './app/views/layouts/closure.phtml'
?>