<?php
    require_once './app/views/layouts/usersMain.phtml';
    $principal = new PrincipalController;
    $school = $principal->find_school($_SESSION['school_id']);
?>

<section class="school-info-section">
    <div class="overlay-modal"></div>
    <section class="up-section">
        <div class="icon-back">
            <a href="<?= URL ?>user/settings">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-left-icon lucide-arrow-left"><path d="m12 19-7-7 7-7"/><path d="M19 12H5"/></svg>

                <p>Voltar</p>
            </a>
        </div>
        <h4>Dados da Escola</h4>
        <p>Editar informações da instituição</p>
    </section>
    <!-- PERSONAL INFORMATION -->
    <section class="personal-info-card">
        <div class="title-area">
            <div class="logo-name-school-area">
                <div class="logo-img">
                    <img src="" alt=" ">
                </div>
                <div class="title-desc">
                    <h4>Informações da Escola</h4>
                    <p>Gerir os dados da instituição</p>
                </div>
            </div>
            <div class="btn-edit-info">
                <button id="btn-edit-info-admin">Editar Informações</button>
            </div>
        </div>
        <!--EDIT ADMIN MODAL-->
        <div class="edit-modal" id="edit-admin-modal">
            <div class="desc-form">
                <h3>Editar Informações</h3>
                <p>Edite as informações da Instituição</p>
                <img src="<?= URL ?>public/assets/icons/x.png" alt="" class="close-modal-icon">
            </div>
            <form action="<?= URL ?>principal/edit_school" method="post" enctype="multipart/form-data">
                <div class="input-box">
                    <label for="schoolName">Nome da Escola</label>
                    <input type="text" name="name" id="schoolName" placeholder="Digite o nome da Escola" value="<?= $school['nome'] ?>">
                </div>

                <div class="input-box">
                    <label for="schoolEmail">Endereço</label>
                    <input type="text" name="address" id="schoolEmail" placeholder="Digite o endereço da Escola" value="<?= $school['endereco'] ?>">
                </div>
                <div class="input-box">
                    <label for="schoolTelefone_1">Telefone</label>
                    <input type="tel" name="contact_1" id="schoolTelefone_1" placeholder="+244 XXX XXX XXX" value="<?= $school['contacto_1'] ?>">
                </div>
                <div class="input-box">
                    <label for="schoolTelefone_2">Telefone Secundário</label>
                    <input type="tel" name="contact_2" id="schoolTelefone_2" placeholder="+244 XXX XXX XXX" value="<?= $school['contacto_2'] ?>">
                </div>

                <div class="input-box">
                    <label for="">Logotipo da Escola</label>
                    <label for="fotoFile" class="labelFile">
                        <input type="file" name="photo" id="fotoFile" class="fotoFile" hidden>
                        Escolher ficheiro.
                        <span class="fileName">Nenhum ficheiro escolhido</span>
                    </label>
                </div>

                <input type="hidden" name="id" value="<?= $school['id'] ?>">
                <input type="hidden" name="current_photo" id="current_photo">

                <div class="final-btn-actions">
                    <button type="button" class="btn" id="btn-cancel">Cancelar</button>
                    <button type="submit" class="btn" id="btn-create">Gravar alterações</button>
                </div>
            </form>
        </div>
        <!--INFO SCHOOL ACCOUNT-->
        <div class="school-info-area">
            <div class="title">
                <h4>Dados Básicos</h4>
            </div>
            <div class="data-area">
                <div class="data">
                    <p>Nome da Escola</p>
                    <h4><?= $school['nome'] ?></h4>
                </div>
                <div class="data">
                    <p>Endereço</p>
                    <h4><?= $school['endereco'] ?></h4>
                </div>
                <div class="data">
                    <p>Telefone</p>
                    <h4><?= $school['contacto_1'] ?></h4>
                </div>
                <div class="data">
                    <p>Telefone Secundário</p>
                    <h4><?= empty($school['contacto_2']) ? '---' : $school['contacto_2'] ?></h4>
                </div>
            </div>
        </div>
    </section>
    <!-- ACCOUNT INFORMATION -->
    <section class="account-info-card">
        <div class="title-desc">
            <h4>Status da Escola</h4>
        </div>
        <div class="account-info-area">
            <div class="account-info">
                <h5>ID da Escola</h5>
                <p><?= $school['id'] ?></p>
            </div>
            <div class="account-info">
                <h5>Status</h5>
                <p><?= empty($school['deleted_at']) ? 'Activa' : 'Inactiva'?></p>
            </div>
            <div class="account-info">
                <h5>Data de Criação</h5>
                <p><?= $school['created_at'] ?></p>
            </div>
        </div>
    </section>
</section>

<?php require_once './app/views/layouts/closure.phtml' ?>