<?php
require_once './app/views/layouts/adminMain.phtml'
?>

<section class="painel-dash">
    <section class="dash-info">
        <div class="header-painel">
            <div class="title">
                <h2>Painel de Administração</h2>
                <p>Gestão de escolas e usuários do sistema</p>
            </div>
            <div class="role-info">
                <img src="" alt=" ">
                <p>Administrador</p>
            </div>
        </div>
        <div class="statistics-info">
            <div class="cards-info">
                <p>Total algo</p>
                <h2>3</h2>
            </div>
            <div class="cards-info">
                <p>Total algo</p>
                <h2>3</h2>
            </div>
            <div class="cards-info">
                <p>Total algo</p>
                <h2>3</h2>
            </div>
            <div class="cards-info">
                <p>Total algo</p>
                <h2>3</h2>
            </div>
            <div class="cards-info">
                <p>Total algo</p>
                <h2>3</h2>
            </div>
            <div class="cards-info">
                <p>Total algo</p>
                <h2>3</h2>
            </div>
        </div>
    </section>
    <section class="list-info">
        <div class="change-list">
            <ul class="school-user-nav">
                <li class="school-user-nav-item"><a href="" class="school-user-nav-link"><span><img src="" alt=" "></span>Escolas</a></li>
                <li class="school-user-nav-item"><a href="" class="school-user-nav-link"><span><img src="" alt=" "></span>Usuários</a></li>
            </ul>
        </div>
        <div class="search-add-area">

        </div>
        <div class="list">

        </div>
    </section>
</section>

<?php
require_once './app/views/layouts/closure.phtml'
?>