<?php require_once './app/views/layouts/usersMain.phtml' ?>

<div class="feed-wrapper">
    <div class="overlay"></div>
    <section id="feed-section">
        <div class="header-feed">
            <div class="title-feed">
                <h2>Feed</h2>
                <p>Publicações e comunicados da sua escola</p>
            </div>
            <button class="btn-new-publish">
                <img src="" alt=" ">
                Nova Publicação
            </button>
        </div>
        <div class="feed-modal">
            <div class="feed-modal-header">
                <h3>Nova Publicação</h3>
                <p>Compartilhe conteúdo com a comunidade escolar.</p>

                <button class="close-icon-btn">
                    <img src="<?= URL ?>public/assets/images/x.png" alt="close-icon">
                </button>
            </div>
            <form action="" class="publication-form">
                <div class="input-box">
                    <label for="type-publication">Tipo de Publicação *</label>
                    <select name="" id="type-publication">
                        <option value="">Publicação Normal</option>
                        <option value="">Aviso/Comunicado</option>
                    </select>
                </div>
                <div class="input-box">
                    <label for="publication-content">Conteúdo *</label>
                    <textarea name="" id="publication-content" placeholder="O que deseja compartilhar?"></textarea>
                </div>
                <div class="input-box">
                    <label for="">Anexos</label>
                    <label for="publication-file" class="labelFile">
                        <input type="file" name="photo" id="publication-file" class="fotoFile" hidden>
                        Anexar Ficheiros.
                        <span class="fileName">Nenhum ficheiro escolhido</span>
                    </label>
                </div>
                <div class="btn-publish-box">
                    <button>Cancelar</button>
                    <button>Publicar</button>
                </div>
            </form>
        </div>
        <div class="tabs-publication">
            <button class="tab-publication">Todas (3)</button>
            <button class="tab-publication">
                <img src="" alt=" ">
                Comunicados (2)
            </button>
        </div>
        <div class="publication-cards">
            <div class="publication-card">
                <div class="header-publication-card">
                    <div class="info-user-publication-card">
                        <div class="img-user">
                            <img src="" alt=" ">
                        </div>
                        <div class="name-user">
                            <h4>Prof. Daniel Silongwa</h4>
                            <p>Published time</p>
                        </div>
                        <div class="publication-type-info">
                            Comunicado
                        </div>
                    </div>
                    <div class="options-publication-card">
                        . 
                        . 
                        . 
                    </div>
                </div>
                <div class="publication-card-content">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus unde fugit ea, dolorem vitae atque laboriosam sit reiciendis..</p>
                </div>
                <div class="reactions-info">
                    Exemplo
                </div>
                <div class="reaction-actions">
                    <button class="reaction-option">
                        <img src="" alt=" ">
                        <p>Gosto</p>
                    </button>
                    <button class="reaction-option">
                        <img src="" alt=" ">
                        <p>Adoro</p>
                    </button>
                    <button class="reaction-option">
                        <img src="" alt=" ">
                        <p>Comentar</p>
                    </button>
                </div>
                <div class="coment-area">
                    <div class="img-user">
                        <img src="" alt=" ">
                    </div>
                    <div class="coment-box">
                        <input type="text" class="text" placeholder="Escreva um comentário">
                        <button type="submit" class="btn-coment">Publicar</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<?php require_once './app/views/layouts/closure.phtml' ?>