<?php require_once './app/views/layouts/usersMain.phtml' ?>

<div class="feed-wrapper">
    <style>
        .selectedFeed{
            background-color: var(--AccentBlue);
        }
        .selectedFeed:hover{
            background-color: var(--AccentBlueHover);
        }
        .selectedFeed a {
            color: var(--Background) !important;
        }
       
        .nav-item:not(.selectedFeed):hover{
            background-color: var(--Muted);
            color: var(--Primary);
        }
    </style>
    <div class="overlay-feed"></div>
    <section id="feed-section">
        <div class="header-feed">
            <div class="title-feed">
                <h2>Feed</h2>
                <p>Publicações e comunicados da sua escola</p>
            </div>
            <button class="btn-new-publish">
                <img src="" alt=" ">
                Nova Publicação
            </button>
        </div>
        <div class="feed-modal">
            <div class="feed-modal-header">
                <h3>Nova Publicação</h3>
                <p>Compartilhe conteúdo com a comunidade escolar.</p>

                <button class="close-icon-btn">
                    <img src="<?= URL ?>public/assets/images/x.png" alt="close-icon">
                </button>
            </div>
            <form action="" class="publication-form">
                <div class="input-box">
                    <label for="type-publication">Tipo de Publicação *</label>
                    <select name="" id="type-publication">
                        <option value="">Publicação Normal</option>
                        <option value="">Aviso/Comunicado</option>
                    </select>
                </div>
                <div class="input-box">
                    <label for="publication-content">Conteúdo *</label>
                    <textarea name="" id="publication-content" placeholder="O que deseja compartilhar?"></textarea>
                </div>
                <div class="input-box">
                    <label for="">Anexos</label>
                    <label for="publication-file" class="labelFile">
                        <input type="file" name="photo" id="publication-file" class="fotoFile" hidden>
                        Anexar Ficheiros.
                        <span class="fileName">Nenhum ficheiro escolhido</span>
                    </label>
                </div>
                <div class="btn-publish-box">
                    <button>Cancelar</button>
                    <button>Publicar</button>
                </div>
            </form>
        </div>
        <div class="tabs-publication">
            <button class="tab-publication">Todas (3)</button>
            <button class="tab-publication">
                <img src="" alt=" ">
                Comunicados (2)
            </button>
        </div>
        <div class="publication-cards">
            <div class="publication-card">
                <div class="header-publication-card">
                    <div class="info-user-publication-card">
                        <div class="img-user">
                            <img src="" alt=" ">
                        </div>
                        <div class="name-user">
                            <h4>Prof. Daniel Silongwa</h4>
                            <p>Published time</p>
                        </div>
                        <div class="publication-type-info">
                            Comunicado
                        </div>
                    </div>
                    <button class="options-publication-card">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-ellipsis-vertical-icon lucide-ellipsis-vertical">
                            <circle cx="12" cy="12" r="1" />
                            <circle cx="12" cy="5" r="1" />
                            <circle cx="12" cy="19" r="1" />
                        </svg>
                        <div class="drop-post-card-actions">
                            <div class="drop-post-card-action">
                                <div class="icon-area">
                                    <img src="" alt=" ">
                                </div>
                                <p>Bloquear comentários</p>
                            </div>
                            <div class="drop-post-card-action">
                                   <div class="icon-area">
                                    <img src="" alt=" ">
                                </div>
                                <p>Remover publicação</p>
                            </div>
                        </div>
                    </button>
                </div>
                <div class="publication-card-content">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus unde fugit ea, dolorem vitae atque laboriosam sit reiciendis..</p>
                    <div class="attachment">
                        <a href="" class="file-info">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-link-icon lucide-link">
                                <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
                                <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
                            </svg>


                            <div class="file-name">
                                <p>Nome do ficheiro</p>
                                <span>Link</span>
                            </div>
                        </a>
                        <a href="" download="" class="btn-download">
                            Baixar
                        </a>
                    </div>
                </div>
                <div class="reactions-info">
                    Reacções
                </div>
                <div class="reaction-actions">
                    <button class="reaction-option thumbs-up" id="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-thumbs-up-icon lucide-thumbs-up"><path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z"/><path d="M7 10v12"/></svg>

                        <p>Gosto</p>
                    </button>
                    <button class="reaction-option favorite">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-heart-icon lucide-heart"><path d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"/></svg>

                        <p>Adoro</p>
                    </button>
                    <button class="reaction-option comment" id="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-circle-icon lucide-message-circle"><path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"/></svg>

                        <p>Comentar</p>
                    </button>
                </div>
                <div class="comment-area">
                    <div class="img-user">
                        <img src="" alt=" ">
                    </div>
                    <div class="comment-box">
                        <textarea name="" id="" placeholder="Escreva um comentário"></textarea>
                        <button type="submit" class="btn-comment">Publicar</button>
                    </div>
                </div>
            </div>
            <div class="publication-card">
                <div class="header-publication-card">
                    <div class="info-user-publication-card">
                        <div class="img-user">
                            <img src="" alt=" ">
                        </div>
                        <div class="name-user">
                            <h4>Prof. Daniel Silongwa</h4>
                            <p>Published time</p>
                        </div>
                        <div class="publication-type-info">
                            Comunicado
                        </div>
                    </div>
                    <button class="options-publication-card">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-ellipsis-vertical-icon lucide-ellipsis-vertical">
                            <circle cx="12" cy="12" r="1" />
                            <circle cx="12" cy="5" r="1" />
                            <circle cx="12" cy="19" r="1" />
                        </svg>
                         <div class="drop-post-card-actions">
                            <div class="drop-post-card-action">
                                <div class="icon-area">
                                    <img src="" alt=" ">
                                </div>
                                <p>Bloquear comentários</p>
                            </div>
                            <div class="drop-post-card-action">
                                   <div class="icon-area">
                                    <img src="" alt=" ">
                                </div>
                                <p>Remover publicação</p>
                            </div>
                        </div>
                    </button>
                </div>
                <div class="publication-card-content">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi magni at alias, quaerat quod tempore atque illum culpa ad veritatis architecto tenetur autem. Iste neque quibusdam consequatur quidem minus quos.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi magni at alias, quaerat quod tempore atque illum culpa ad veritatis architecto tenetur autem. Iste neque quibusdam consequatur quidem minus quos.</p>
                    <div class="attachment">
                        <a href="" class="file-info">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-link-icon lucide-link">
                                <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
                                <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
                            </svg>

                            <div class="file-name">
                                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum rem ab perferendis necessitatibus maxime consectetur aspernatur eius vero, saepe minima suscipit adipisci illo debitis amet est repudiandae, temporibus et voluptas?</p>
                                <span>Link</span>
                            </div>
                        </a>
                        <a href="" download="" class="btn-download">
                            Baixar
                        </a>
                    </div>
                </div>
                <div class="reactions-info">
                    Exemplo
                </div>
                <div class="reaction-actions">
                    <button class="reaction-option thumbs-up" id="">
                         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-thumbs-up-icon lucide-thumbs-up"><path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z"/><path d="M7 10v12"/></svg>
                        <p>Gosto</p>
                    </button>
                    <button class="reaction-option favorite">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-heart-icon lucide-heart"><path d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"/></svg>
                        <p>Adoro</p>
                    </button>
                    <button class="reaction-option comment" id="">
                           <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-circle-icon lucide-message-circle"><path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"/></svg>
                        <p>Comentar</p>
                    </button>
                </div>
                <div class="comment-area">
                    <div class="img-user">
                        <img src="" alt=" ">
                    </div>
                    <div class="comment-box">
                        <textarea name="" id="" placeholder="Escreva um comentário"></textarea>
                        <button type="submit" class="btn-comment">Publicar</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<?php require_once './app/views/layouts/closure.phtml' ?>