<!DOCTYPE html>
<html lang="pt-AO">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduConnect</title>
    <link rel="stylesheet" href="<?= URL ?>public/css/forms.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/tokens.css">

</head>

<body>

    <div class="login-modal">

        <div class="logo">
             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-graduation-cap-icon lucide-graduation-cap"><path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z"/><path d="M22 10v6"/><path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"/></svg>
        </div>

        <h3>EduConnect</h3>
        <p class="subtitle">Plataforma Educacional Multi-Escola</p>
        <a href="<?= URL ?>admin/login" class="admin-link">Entrar como Administrador</a>

        <form action="<?= URL ?>user/login_user" method="post" class="form">
            <div class="input-box">
                <label for="nif">NIF</label>
                <input type="text" placeholder="Seu NIF" id="nif" name="nif">
            </div>

            <div class="input-box">
                <label for="password">Senha</label>
                <input type="password" placeholder="Sua Senha" id="password" name="password" autocomplete="off">
            </div>
            <input type="submit" value="Entrar" class="btn">
        </form>

    </div>

</body>

</html>