<?php
    require_once './app/views/layouts/usersMain.phtml';
?>

<section class="settings-page">
    <div class="title">
        <h2>Configurações</h2>
        <p>Gerir a sua conta e preferências</p>
    </div>
    <div class="setting-cards">
        <div class="setting-card">
            <h4>Conta</h4>
            <a href="<?= URL ?>user/infoAccount" class="redirect-area">
                <div class="settings-info-card">
                    <div class="icon-area">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-icon lucide-user"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>

                    </div>
                    <div class="desc-setting-card">
                        <h4>Minha Conta</h4>
                        <p>Visualizar e editar informações da conta</p>
                    </div>
                </div>
                 <div class="redirect-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right-icon lucide-chevron-right"><path d="m9 18 6-6-6-6"/></svg>

                </div>
            </a>
        </div>
        <div class="setting-card">
            <h4>Segurança</h4>
            <a href="<?= URL ?>user/security" class="redirect-area">
                <div class="settings-info-card">
                    <div class="icon-area">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield-icon lucide-shield"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/></svg>

                    </div>
                    <div class="desc-setting-card">
                        <h4>Segurança</h4>
                        <p>Gerir a segurança da sua conta</p>
                    </div>
                </div>
                 <div class="redirect-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right-icon lucide-chevron-right"><path d="m9 18 6-6-6-6"/></svg>

                </div>
            </a>
        </div>
        <?php if($_SESSION['role'] === 'director'):?>
            <div class="setting-card">
                <h4>Escola</h4>
                <a href="<?= URL ?>principal/infoSchoolAccount" class="redirect-area">
                    <div class="settings-info-card">
                        <div class="icon-area">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-building2-icon lucide-building-2"><path d="M10 12h4"/><path d="M10 8h4"/><path d="M14 21v-3a2 2 0 0 0-4 0v3"/><path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2"/><path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16"/></svg>

                        </div>
                        <div class="desc-setting-card">
                            <h4>Dados da Escola</h4>
                            <p>Editar informações da instituição</p>
                        </div>
                    </div>
                    <div class="redirect-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right-icon lucide-chevron-right"><path d="m9 18 6-6-6-6"/></svg>

                    </div>
                </a>
            </div>
        <?php endif;?>
        <div class="setting-card">
            <h4>Sessão</h4>
            <a href="<?= URL ?>user/logout" class="redirect-area" id="exit-card">
                <div class="settings-info-card">
                    <div class="icon-area">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-log-out-icon lucide-log-out"><path d="m16 17 5-5-5-5"/><path d="M21 12H9"/><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/></svg>

                    </div>
                    <div class="desc-setting-card">
                        <h4>Terminar Sessão</h4>
                        <p>Sair da sua conta</p>
                    </div>
                </div>
                <div class="redirect-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right-icon lucide-chevron-right"><path d="m9 18 6-6-6-6"/></svg>

                </div>
            </a>
        </div>
    </div>
</section>

<?php require_once './app/views/layouts/closure.phtml' ?>