<?php
    require_once './app/views/layouts/usersMain.phtml';
?>

<section class="settings-page">
    <div class="title">
        <h2>Configurações</h2>
        <p>Gerir a sua conta e preferências</p>
    </div>
    <div class="setting-cards">
        <div class="setting-card">
            <h4>Conta</h4>
            <a href="<?= URL ?>user/infoAccount" class="redirect-area">
                <div class="settings-info-card">
                    <div class="icon-area">
                        <img src="" alt=" ">
                    </div>
                    <div class="desc-setting-card">
                        <h4>Minha Conta</h4>
                        <p>Visualizar e editar informações da conta</p>
                    </div>
                </div>
                 <div class="redirect-icon">
                    <img src="" alt=" ">
                </div>
            </a>
        </div>
        <div class="setting-card">
            <h4>Segurança</h4>
            <a href="<?= URL ?>user/security" class="redirect-area">
                <div class="settings-info-card">
                    <div class="icon-area">
                        <img src="" alt=" ">
                    </div>
                    <div class="desc-setting-card">
                        <h4>Segurança</h4>
                        <p>Gerir a segurança da sua conta</p>
                    </div>
                </div>
                 <div class="redirect-icon">
                    <img src="" alt=" ">
                </div>
            </a>
        </div>
        <?php if($_SESSION['role'] === 'director'):?>
            <div class="setting-card">
                <h4>Escola</h4>
                <a href="<?= URL ?>principal/infoSchoolAccount" class="redirect-area">
                    <div class="settings-info-card">
                        <div class="icon-area">
                            <img src="" alt=" ">
                        </div>
                        <div class="desc-setting-card">
                            <h4>Dados da Escola</h4>
                            <p>Editar informações da instituição</p>
                        </div>
                    </div>
                    <div class="redirect-icon">
                        <img src="" alt=" ">
                    </div>
                </a>
            </div>
        <?php endif;?>
        <div class="setting-card">
            <h4>Sessão</h4>
            <a href="<?= URL ?>user/logout" class="redirect-area" id="exit-card">
                <div class="settings-info-card">
                    <div class="icon-area">
                        <img src="" alt=" ">
                    </div>
                    <div class="desc-setting-card">
                        <h4>Terminar Sessão</h4>
                        <p>Sair da sua conta</p>
                    </div>
                </div>
                <div class="redirect-icon">
                    <img src="" alt=" ">
                </div>
            </a>
        </div>
    </div>
</section>

<?php require_once './app/views/layouts/closure.phtml' ?>