<?php
    require_once './app/views/layouts/usersMain.phtml';
    $class_id = $_SESSION['class_id'];

    $class = new ClassController;
    $messages = new MessageController;
    $chats = new ChatController;

    $class_chat = $chats->get_chat($class_id, $_SESSION['school_id']);
    $class_data = $class->get_class_data($class_id, $_SESSION['school_id']);
    $students = $class->get_class_students($class_id);
?>

<div class="current-class-wrapper">
    <div class="overlay-feed"></div>
    <div class="overlay-current-class"></div>
    <section id="current-class-section">
        <div class="icon-back">
            <a href="<?= URL ?>student/classes">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-left-icon lucide-arrow-left">
                    <path d="m12 19-7-7 7-7" />
                    <path d="M19 12H5" />
                </svg>

                <p>Voltar</p>
            </a>
        </div>
        <div class="class-info">
            <div class="top-side">
                <div class="nome-desc-class">
                    <h4><?= $class_data['class'] ?></h4>
                </div>
            </div>
            <div class="info-nome-teacher">
                <div class="teacher-photo">
                    <?php if ($class_data['foto'] !== "null"):?>
                        <img src="<?= URL. "public/". $class_data['foto'] ?>">
                    <?php else:?>
                        <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                            <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                            <circle cx="12" cy="11" r="4" />
                            <circle cx="12" cy="12" r="10" />
                        </svg>
                    <?php endif;?>
                </div>
                <div class="nome-teacher">
                    <h3><?= $class_data['teacher'] ?></h3>
                    <p>Professor</p>
                </div>
            </div>
        </div>
        <div class="tabs-class">
            <button class="tab-class activeClass" data-current-class="pub-class">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-paperclip-icon lucide-paperclip">
                    <path d="m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551" />
                </svg>


                <p>Anexos (1)</p>
            </button>
            <button class="tab-class" data-current-class="chat-section">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-square-icon lucide-message-square">
                    <path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z" />
                </svg>

                <p>Chat</p>
            </button>
            <button class="tab-class" data-current-class="students-manegement">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users-icon lucide-users">
                    <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                    <path d="M16 3.128a4 4 0 0 1 0 7.744" />
                    <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
                    <circle cx="9" cy="7" r="4" />
                </svg>

                <p>Membros (<?= $class_data['students'] ?>)</p>
            </button>
        </div>
        <!--CHAT SECTION-->
        <div class="chat-section class-content">
            <div class="messages-box" id="messages-box"></div>
            <div class="send-message-box">
                <div class="img-profile">
                    <?php if ($_SESSION['photo'] !== "null"):?>
                        <img src="<?= URL. "public/". $_SESSION['photo'] ?>">
                    <?php else:?>
                        <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                            <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                            <circle cx="12" cy="11" r="4" />
                            <circle cx="12" cy="12" r="10" />
                        </svg>
                    <?php endif;?>
                </div>
                <form action="<?= URL ?>message/send_message/<?= $class_id ?>/<?= $_SESSION['role'] ?>" method="POST" class="message-input">
                    <div class="input-box">
                        <textarea name="content" class="fileName" id="msg-content" placeholder="Escreva uma mensagem"></textarea>
                    </div>

                    <input type="hidden" name="chat" value="<?= $class_chat ?>">
                    <input type="hidden" name="school" value="<?= $_SESSION['school_id'] ?>">
                    <input type="hidden" name="user" value="<?= $_SESSION['id'] ?>">

                    <div class="msg-action-btns">
                        <label for="publication-file" class="labelFile">
                            <input type="file" name="file" id="publication-file" class="fotoFile" hidden>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-paperclip-icon lucide-paperclip">
                                <path d="m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551" />
                            </svg>
                            Anexar
                        </label>
                        <button type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-send-icon lucide-send">
                                <path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z" />
                                <path d="m21.854 2.147-10.94 10.939" />
                            </svg>
                            <p>Enviar</p>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <!--STUDENTS MANAGEMENT-->
        <div class="students-manegement class-content" id="">
            <?php if (!empty($students)): ?>
                <?php foreach ($students as $s): ?>
                    <div class="student-item">
                        <div class="info-student">
                            <div class="student-profile">
                                <?php if ($s['foto'] !== "null"):?>
                                    <img src="<?= URL. "public/". $s['foto'] ?>">
                                <?php else:?>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                                        <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                                        <circle cx="12" cy="11" r="4" />
                                        <circle cx="12" cy="12" r="10" />
                                    </svg>
                                <?php endif;?>
                            </div>
                            <div class="student-name-email">
                                <h4><?= $s['nome'] ?></h4>
                                <p><?= $s['email'] ?></p>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>

    </section>
</div>

<input type="hidden" id="school" value="<?= $_SESSION['school_id'] ?>">
<input type="hidden" id="chat" value="<?= $class_chat ?>">
<input type="hidden" id="user" value="<?= $_SESSION['id'] ?>">
<script src="<?= URL ?>public/js/chatRealTime.js"></script>

<?php require_once './app/views/layouts/closure.phtml' ?>