<?php
    require_once './app/views/layouts/usersMain.phtml';
    $class = new ClassController;
    $classes = $class->get_students_classes($_SESSION['id']);
?>

<div class="class-wrapper">
    <div class="overlay-class"></div>
    <style>
        .selectedClass {
        background-color: var(--AccentBlue);
        }
        
        .selectedClass:hover {
            background-color: var(--AccentBlueHover);
        }

        li:not(.selectedClass):hover {
            background-color: var(--Muted);
        }

        .selectedClass a {
            color: var(--Background) !important;
        }
    </style>
    <section id="class-section">
        <div class="header-class">
            <div class="title-class">
                <h2>Turmas</h2>
                <p>Turmas que faz parte</p>
            </div>
        </div>

        <!--SEARCH CLASS BOX-->
        <div class="search-class">
            <div class="icon-search-class">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-search-icon lucide-search"><path d="m21 21-4.34-4.34"/><circle cx="11" cy="11" r="8"/></svg>

            </div>
            <input type="text" name="searcClasses" id="searcClasses" placeholder="Pesquisar Turmas">
        </div>

        <!--CLASS CARDS SECTION-->
        <div class="class-cards" id="classResults">
              <?php if (!empty($classes)):?>
                <?php foreach ($classes as $s_class):?>
                    <a href="<?= URL ?>student/class/<?= $s_class['id'] ?>" class="class-card">
                        <h3><?= $s_class['class'] ?></h3>
                        <div class="prof-info">
                            <div class="prof-profile-img">
                                <?php if ($s_class['teacher_photo'] !== "null"):?>
                                    <img src="<?= URL. "public/". $s_class['teacher_photo'] ?>">
                                <?php else:?>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                                        <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                                        <circle cx="12" cy="11" r="4" />
                                        <circle cx="12" cy="12" r="10" />
                                    </svg>
                                <?php endif;?>
                            </div>
                            <h4><?= $s_class['teacher'] ?></h4>
                        </div>
                        <div class="students-info">
                            <div class="icon-students">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users-icon lucide-users"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><path d="M16 3.128a4 4 0 0 1 0 7.744"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/></svg>

                            </div>
                            <h4><?= $s_class['students'] === 1 ? "{$s_class['students']} aluno" : "{$s_class['students']} alunos" ?></h4>
                        </div>
                    </a>
               <?php endforeach;?>
            <?php endif;?>
        </div>
    </section>
</div>
<input type="hidden" id="userId" value="<?= $_SESSION['id'] ?>">
<input type="hidden" id="userRole" value="aluno">
<input type="hidden" id="type" value="classSearch">
<input type="hidden" name="url" id="url" value="<?= URL ?>">
<script src="<?= URL ?>public/js/searchClasses.js"></script>

<?php require_once './app/views/layouts/closure.phtml' ?>
