<!DOCTYPE html>
<html lang="pt-AO">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>eduConnect</title>
    <link rel="stylesheet" href="<?= URL ?>public/css/app.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/tokens.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/admin.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/settings.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/infoAccount.css">
    <script src="<?= URL ?>public/js/app.js" defer></script>
    <script src="<?= URL ?>public/js/admin.js" defer></script>
    <script src="<?= URL ?>public/js/passwordsControl.js" defer></script>
    <link rel="shortcut icon" href="<?= URL ?>public/assets/icons/favicon.svg" type="image/svg+xml">

</head>

<body>
    <div class="layout-admin">
        <aside class="sideBar">
            <div class="show-info">
                <div class="logo-system">
                    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-graduation-cap-icon lucide-graduation-cap"><path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z"/><path d="M22 10v6"/><path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"/></svg>
                    <h2>EduConnect</h2>
                    <img src="<?= URL ?>public/assets/icons/x.png" id="close-menu">
                </div>
                <div class="info-profile">
                    <div class="profile-poto">
                        <?php if ($_SESSION['photo'] !== "null"):?>
                            <img src="<?= URL . 'public/' . $_SESSION['photo'] ?>">
                        <?php else:?>
                            <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round-icon lucide-circle-user-round">
                                <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                                <circle cx="12" cy="11" r="4" />
                                <circle cx="12" cy="12" r="10" />
                            </svg>
                        <?php endif;?>
                    </div>
                    <div class="user-details">
                        <h3><?= $_SESSION['name'] ?></h3>
                        <span>admin</span>
                    </div>
                </div>
            </div>
            <nav class="nav-bar">
                <div class="main-nav">
                    <ul class="nav-list">
                        <li class="nav-item visitedPainelAdmin" data-link="painel"><a href="<?= URL ?>admin/index" class="nav-link">
                                <span class="nav-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield-icon lucide-shield">
                                        <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
                                    </svg>
                                </span>Painel Admin</a></li>
                    </ul>
                </div>
                <div class="set-nav">
                    <ul class="nav-list">
                        <li class="nav-item">
                            <a href="<?= URL ?>admin/settings" class="nav-link">
                                <span class="nav-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-settings-icon lucide-settings">
                                        <path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915" />
                                        <circle cx="12" cy="12" r="3" />
                                    </svg>

                                </span>Configurações
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?= URL ?>admin/logout" class="nav-link">
                                <span class="nav-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-log-out-icon lucide-log-out">
                                        <path d="m16 17 5-5-5-5" />
                                        <path d="M21 12H9" />
                                        <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
                                    </svg>

                                </span>Sair
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </aside>
        <div class="overlay"></div>
        <header class="header">
            <div class="open-menu">
                <img src="<?= URL ?>public/assets/icons/menu.png" alt="icon-menu">
            </div>
            <h2>EduConnect</h2>
        </header>
        <main class="main">