<!DOCTYPE html>
<html lang="pt-AO">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>eduConnect</title>
    <link rel="stylesheet" href="<?= URL ?>public/css/appUsers.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/tokens.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/infoAccount.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/infoSchoolAccount.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/director.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/settings.css">
    <link rel="stylesheet" href="<?= URL ?>public/css/settingsUsers.css">
    <script src="<?= URL ?>public/js/app.js" defer></script>
    <script src="<?= URL ?>public/js/admin.js" defer></script>
    
</head>

<body>
    <div class="layout-admin">
        <aside class="sideBar">
            <div class="show-info">
                <div class="logo-system">
                    <h2>EduConnect</h2>
                    <img src="<?= URL ?>public/assets/images/x.png" alt=" " id="close-menu">
                </div>
                <div class="info-profile">
                    <div class="profile-poto">
                        <img src="" alt=" ">
                    </div>
                    <div class="user-details">
                        <h3><?= $_SESSION['name'] ?></h3>
                        <span>nivel acesso</span>
                    </div>
                </div>
            </div>
            <nav class="nav-bar">
                <div class="main-nav">
                    <ul class="nav-list">
                        <li class="nav-item" data-link="painel"><a href="<?= URL ?>user/feed" class="nav-link"><span class="nav-icon"><img src="" alt=" "></span>Feed</a></li>
                        <li class="nav-item visited" data-link="painel"><a href="<?= URL ?>user/index" class="nav-link"><span class="nav-icon"><img src="" alt=" "></span>Gestão Escola</a></li>
                        <li class="nav-item" data-link="painel"><a href="<?= URL ?>user/turmas" class="nav-link"><span class="nav-icon"><img src="" alt=" "></span>Turmas</a></li>
                        <li class="nav-item" data-link="painel"><a href="<?= URL ?>user/mensagens" class="nav-link"><span class="nav-icon"><img src="" alt=" "></span>Mensagens</a></li>
                    </ul>
                </div>
                <div class="set-nav">
                    <ul class="nav-list">
                        <li class="nav-item"><a href="<?= URL ?>user/settings" class="nav-link"><span class="nav-icon"><img src="" alt=" "></span>Configurações</a></li>
                        <li class="nav-item"><a href="<?= URL ?>user/logout" class="nav-link"><span class="nav-icon"><img src="" alt=" "></span>Sair</a></li>
                    </ul>
                </div>
            </nav>
        </aside>
        <div class="overlay"></div>
        <header class="header">
            <div class="open-menu">
                <img src="<?= URL ?>public/assets/images/menu.png" alt="icon-menu">
            </div>
            <h2>EduConnect</h2>
        </header>
        <main class="main">
        <section class="head-section">
            <div class="icon-school-area">
                <img src="" alt=" ">
            </div>
            <h3>Nome da Escola</h3>
        </section>